version: '2'

services:
  database:
    image: mysql:5.7
    volumes:
      - db-volume2:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - internal
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'bazdan#20'
  website:
    image: theredfoxlee/flask:1.0
    volumes:
      - ./flask:/app
    networks:
      - internal
    ports:
      - 80:80
    depends_on:
      - database

volumes:
  db-volume2:

networks:
  internal:
