version: '2'

services:
  website:
    image: theredfoxlee/flask:1.0
    volumes:
      - ./app:/app
    networks:
      - internal
    ports:
      - 80:80
  database:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - internal
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'bazdan#20'

  volumes:
    db-volume:

  networks:
    internal:

